<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Blog'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/style.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/functions.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>

    <div class="blog-masthead">
        <div class="container">
            <nav class="blog-nav" role="navigation">
                <a class="blog-nav-item" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                <a class="blog-nav-item" href="<?php echo $this->basePath('/blog'); ?>"><?php echo $this->translate('Blog') ?></a>
            </nav>
        </div>
    </div>

    <div class="container">
        <?php echo $this->content; ?>
    </div> <!-- /container -->

    <footer class="blog-footer">
        <p>&copy; <?php echo date('Y') ?> Blog template built for Bootstrap.</p>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
        <p>
            <a href="#">Back to top</a>
        </p>
    </footer>

    <?php echo $this->inlineScript() ?>
</body>
</html>
