<h1>Blog</h1>

<?php foreach ($this->posts as $key => $post) : ?>
<article id="post-<?= $post->getId() ?>" class="panel panel-default">
    <div class="panel-heading">
        <strong><?= $post->getTitle() ?></strong>
    </div>
    <div class="panel-body">
        <p><?= $post->getContent() ?></p>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-left"><strong>Published:</strong> <?= $post->getDate()->format('Y.m.d. H:i'); ?></div>
        <div class="pull-right"><a href="<?php echo $this->basePath() . '/blog/' . $post->getId(); ?>">View</a></div>
    </div>
</article>
<?php endforeach; ?>