<div class="blog-header">
    <h1 class="blog-title">Welcome to my Blog</h1>
    <p class="lead blog-description">This is a web application built with Zend Framework 2 and Doctrine as ORM. You can post, edit or delete articles, or just leave us a reply for them as a comment.</p>
</div>

<div class="row blog-main">

    <?php foreach ($this->posts as $key => $post) : ?>

    <article id="post-<?= $post->getId() ?>" class="blog-post">
        <h2 class="blog-post-title"><?= $post->getTitle() ?></h2>
        <p class="blog-post-meta"><?= $post->getDate()->format('Y.m.d. H:i'); ?></p>

        <p><?= $post->getContent() ?></p>

        <div class="btn btn-default">
            <a href="<?php echo $this->basePath('blog/' . $post->getId()); ?>">View full post</a>
        </div>
    </article>

    <?php endforeach; ?>

</div>