<?php 
$title = 'Delete post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete '<?php echo $this->escapeHtml($post->getTitle()); ?>'?</p>
<?php
$url = $this->url('post', array(
    'action' => 'delete',
    'id'     => $post->getId(),
));
?>
<form action="?" method="post">
    <input class="btn btn-danger" type="submit" name="del" value="Yes" />
    <input class="btn btn-success" type="submit" name="del" value="No" />
</form>